spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/gutenberg?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
